name: 'Render Jinja2 Workflow Template'

on:
  workflow_dispatch:  # Manual trigger

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install jinja2-cli
        run: |
          pip install jinja2-cli

      - name: Render Jinja2 template
        run: |
          jinja2 -D folders="python/app/folder1:python,java/app/folder2:java,go/app/folder3:go" test.yaml.j2 > folder-test-loop.yaml

      - name: Show rendered output
        run: cat folder-test-loop.yaml
